"""
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Answer: 4613732
"""

def sum_of_even_fibonacci_terms(limit):
	x = y = 1
	total = 0
	while y < limit:
		sum_ = x + y
		if sum_ % 2 == 0:
			total += sum_
		z = sum_
		x = y
		y = z
	return total

print sum_of_even_fibonacci_terms(4000000)
